@startuml
participant App
participant "v8::Script" as v8_script
participant "v8::ScriptCompiler" as v8_scriptCompiler
participant "v8::internal::Compiler" as internal_Compiler
participant "v8::internal" as internal
participant "v8::parsing" as parsing
App -> v8_script : Compile
v8_script -> v8_scriptCompiler : Compile
v8_scriptCompiler -> v8_scriptCompiler : CompileUnboundInternal
v8_scriptCompiler -> internal_Compiler : GetSharedFunctionInfoForScript
internal_Compiler -> internal : GetSharedFunctionInfoForScriptImpl
internal -> internal : CompileScriptOnMainThread
internal -> internal_Compiler : CompileToplevel
internal_Compiler -> internal : CompileToplevel
internal -> parsing : ParseProgram
internal -> internal : IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs
@enduml
